pipeline{
    agent any
    stages{
        stage('Git clone'){
            steps{
                bat 'git clone https://github.com/vishwanath0303/simple-java-maven-app.git'
            }
        }
        
        stage('maven build'){
            steps{
                // bat 'simple-java-maven-app'
                
             bat 'cd ${Workspace}\simple-java-maven-app'
                 bat 'mvn clean package'
            }
        }
        stage('Create Dockerimage'){
            steps{
                sh 'docker build -t vkulkarni0303/springboot:latest .'
            }
        }
        
    }
}
