pipeline{
    agent any
    stages{
        stage('Git clone'){
            steps{
                sh 'git clone https://github.com/vishwanath0303/simple-java-maven-app.git'
            }
        }
        
        stage('maven build'){
            steps{
               // sh 'simple-java-maven-app'
                
                // sh 'cd ${Workspace}\HelloWorld-Springboot-App'
                 sh 'mvn package'
            }
        }
        stage('Create Dockerimage'){
            steps{
                sh 'docker build -t vkulkarni0303/springboot:latest .'
            }
        }
        
    }
}
